name: Deploy pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Dependencies
        run: pnpm i

      - name: Install slidev
        run:  pnpm add -g @slidev/cli

      - name: Build slidev examples
        run: pnpm run gen:demos

      - name: Convert index.md to index.html
        uses: jd-solanki/gh-action-md-to-html@main
        with:
          files: '[["dist/index.md", "dist/index.html"]]'
          title: 'Slidev Theme Dracula | Examples'
          favicon: https://draculatheme.com/static/img/favicon.ico

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2